name: build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build:
    permissions:
      packages: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        run: >
          echo ${{ secrets.GITHUB_TOKEN }} | 
          docker login ghcr.io --username dangmai --password-stdin
      - name: Publish functions
        run: >
          OWNER="dangmai" 
          TAG="latest"
          faas-cli publish
          --extra-tag ${{ github.sha }}
          --platforms linux/arm/v7,linux/arm64,linux/amd64
